### ISSUE TITLE
v2 releases have missing files in custom node folder.

### ISSUE THREAD

**Issue by SligtEye** [9thAzure/Complex_Shape_Creation#50]
v2 releases have missing files in custom node folders, rendering the releases non functional. Asset library in Godot4.2 downloads a nonfunctional release.  Adding the missing files from git seems to work.

**Comment by 9thAzure** [comment]
#51 Fixes this. I have updated both of the Releases to incorporate this change, so they should hopefully be working now.

Thanks for telling me this.
