### ISSUE TITLE
Make lines not bypass `drawn_arc = 0` stopping regenerating in `RegularCollisionShape2D`

### ISSUE THREAD

**Issue by deon-l** [9thAzure/Complex_Shape_Creation#9]
Currently, using lines (setting `vertices_count` to 2) bypasses the restriction that when `drawn_arc` is set to 0, shapes will not be regenerated. You can still change the properties of the line, and you can switch the shape into a line.

**Comment by 9thAzure** [comment]
Fixed this at some pr...
